# Generated by Django 5.1.15 on 2026-09-16 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Topic Tag',
                'verbose_name_plural': 'Topic Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('prompt_text', models.TextField(help_text='Spoken prompt instructions for the learner')),
                ('skill_focus', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('fluency', 'Fluency'), ('pronunciation', 'Pronunciation'), ('mixed', 'Mixed')], default='mixed', help_text='Primary skill focus of the prompt', max_length=20)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Mastery')], default='B1', help_text='Target CEFR level (A1 to C2)', max_length=2)),
                ('source', models.CharField(choices=[('static', 'Pre-curated'), ('generated', 'AI Adaptive')], default='static', max_length=20)),
                ('vocabulary_hints', models.JSONField(blank=True, default=list, help_text='Target vocabulary list used for prompt context and transcription biasing')),
                ('min_duration_seconds', models.PositiveIntegerField(default=15, help_text='Suggested minimum speaking duration in seconds')),
                ('max_duration_seconds', models.PositiveIntegerField(default=120, help_text='Suggested maximum speaking duration in seconds')),
                ('language', models.ForeignKey(help_text='Target language of the exercise prompt', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='authentication.language')),
                ('topic_tags', models.ManyToManyField(blank=True, help_text='Normalized topic category tags', related_name='exercises', to='exercises.topictag')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['cefr_level', 'skill_focus', 'id'],
            },
        ),
    ]
