# Generated by Django 5.1.15 on 2026-09-21 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguage',
            name='language',
            field=models.ForeignKey(help_text='Protected from deletion if active user language records reference it', on_delete=django.db.models.deletion.PROTECT, related_name='user_languages', to='authentication.language'),
        ),
    ]
