# Generated by Django 5.1.15 on 2026-09-16 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_title', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('conversation_summary', models.TextField(blank=True, default='')),
                ('turn_counter', models.PositiveIntegerField(default=0, help_text='Incremented under row lock before creating a turn to prevent race conditions')),
                ('snapshot_prompt_text', models.TextField(blank=True, default='', help_text='Snapshots the Exercise prompt so historical sessions remain intact if Exercise is edited')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_sessions', to='exercises.exercise')),
                ('user_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sessions', to='authentication.userlanguage')),
            ],
            options={
                'verbose_name': 'Conversation Session',
                'verbose_name_plural': 'Conversation Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=10)),
                ('turn_sequence', models.PositiveIntegerField(help_text='1-indexed sequence order within the session')),
                ('text_content', models.TextField(blank=True, default='')),
                ('llm_model_version', models.CharField(blank=True, help_text="Exact upstream version hash or model ID, e.g. 'gpt-4o-2024-05-13' or 'gemini-1.5-flash-002'", max_length=100, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, help_text='Inference response latency in milliseconds', null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, help_text='Prompt token count', null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, help_text='Completion token count', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='recordings.conversationsession')),
            ],
            options={
                'verbose_name': 'Conversation Turn',
                'verbose_name_plural': 'Conversation Turns',
                'ordering': ['session', 'turn_sequence'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audio_file', models.FileField(help_text='Cloud storage pointer/URL to S3 or file storage', max_length=1024, upload_to='recordings/%Y/%m/%d/')),
                ('mime_type', models.CharField(default='audio/webm', help_text='Audio MIME type, e.g. audio/webm or audio/mp4', max_length=50)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Calculated duration in seconds', null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, help_text='Audio file size in bytes', null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], db_index=True, default='uploaded', help_text='Indexed for queue polling', max_length=20)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error diagnostics if analysis fails')),
                ('turn', models.OneToOneField(blank=True, help_text='Associated user conversation turn', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='recordings.conversationturn')),
            ],
            options={
                'verbose_name': 'Recording',
                'verbose_name_plural': 'Recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeaknessTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weakness_tags', to='authentication.language')),
            ],
            options={
                'verbose_name': 'Weakness Tag',
                'verbose_name_plural': 'Weakness Tags',
                'ordering': ['language', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Flags the active result among multiple runs')),
                ('estimated_cefr', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Mastery')], default='B1', help_text='Estimated CEFR level for this response', max_length=2)),
                ('grammar_feedback', models.JSONField(blank=True, default=dict, help_text='Structured grammar evaluation, errors, and suggested corrections')),
                ('vocabulary_feedback', models.JSONField(blank=True, default=dict, help_text='Structured vocabulary sophistication and recommendations')),
                ('fluency_metrics', models.JSONField(blank=True, default=dict, help_text='Calculated metrics: wpm, pause_count, avg_pause_ms, filler_count')),
                ('word_timestamps', models.JSONField(blank=True, default=list, help_text='List of word objects with start_offset and end_offset in seconds')),
                ('asr_model_version', models.CharField(blank=True, default='', help_text="Exact speech-to-text model version, e.g. 'whisper-large-v3' or 'gemini-1.5-flash'", max_length=100)),
                ('llm_model_version', models.CharField(blank=True, default='', help_text="Exact analysis LLM version, e.g. 'gpt-4o-2024-05-13'", max_length=100)),
                ('prompt_version', models.CharField(blank=True, default='', help_text='Version identifier of prompt template used', max_length=50)),
                ('latency_asr_ms', models.PositiveIntegerField(blank=True, help_text='Transcription latency in ms', null=True)),
                ('latency_llm_ms', models.PositiveIntegerField(blank=True, help_text='Analysis LLM latency in ms', null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, help_text='Prompt tokens consumed', null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, help_text='Output tokens generated', null=True)),
                ('raw_llm_response', models.JSONField(blank=True, default=dict, help_text='Raw verbatim upstream response payload for debugging and verification')),
                ('recording', models.ForeignKey(help_text='Foreign Key allows re-running analysis on the same recording', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='recordings.recording')),
                ('weakness_tags', models.ManyToManyField(blank=True, help_text='Normalized weakness tags identified during analysis', related_name='analysis_results', to='recordings.weaknesstag')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversationturn',
            constraint=models.UniqueConstraint(fields=('session', 'turn_sequence'), name='unique_session_turn_sequence'),
        ),
        migrations.AddConstraint(
            model_name='weaknesstag',
            constraint=models.UniqueConstraint(fields=('language', 'name'), name='unique_weakness_tag_per_language'),
        ),
        migrations.AddConstraint(
            model_name='analysisresult',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('recording',), name='unique_current_analysis_per_recording'),
        ),
    ]
