# Generated by Django 6.1 on 2026-09-27 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDecisionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='CONTINUE, REMEDIATE, ASK_FOLLOW_UP, INCREASE_DIFFICULTY, GIVE_FEEDBACK', max_length=50)),
                ('target_skill', models.CharField(blank=True, default='', max_length=50)),
                ('target_weakness', models.CharField(blank=True, default='', max_length=100)),
                ('difficulty', models.CharField(blank=True, default='', max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('was_executed', models.BooleanField(default=False, help_text='Whether this decision (e.g. REMEDIATE) was executed into a concrete exercise')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_decisions', to='recordings.conversationsession')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_decisions', to='recordings.conversationturn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Decision Log',
                'verbose_name_plural': 'Agent Decision Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
